import {  Karla } from "next/font/google";
import "./globals.css";

import ConvexClientProvider from "./ConvexClientProvider";

export const metadata = {
  title: "SnipAi",
  description: "Generated by create next app",
  
};

const karla = Karla({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={karla.className}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
