"use client";
import { Button } from "../../components/ui/button";
import React from "react";
import Authentication from "./Authentication";
import { useAuthContext } from "../provider";
import Link from "next/link";
import { motion } from "motion/react";
import { cn } from "../../lib/utils";
import Header from "./Header";
import { Ripple } from "../../components/magicui/ripple";
import { ArrowRightIcon } from "@radix-ui/react-icons";
import { AnimatedShinyText } from "../../components/magicui/animated-shiny-text";
import { FlipWords } from "../../components/ui/flip-words";
import { AuroraText } from "../../components/magicui/aurora-text";

function Hero() {
  return (
    <div>
      <div className="">
        {/* Header */}
        <Header />
      </div>
      <div className="w-full ">
        <RippleDemo />
      </div>
    </div>
  );
}

export function RippleDemo() {
  const { user } = useAuthContext();
  return (
    <div className="relative flex min-h-screen w-full flex-col items-center justify-center overflow-hidden rounded-lg border-none bg-background">
      <div className="z-10 whitespace-pre-wrap text-center font-sarif  tracking-tighter text-white">
        <div className=" flex flex-col justify-center items-center w-full">
          <AnimatedShinyTextDemo />
          <FlipWordsDemo />
          <motion.p className="text-center mt-2 text-lg text-gray-300 relative z-20 px-4 lg:px-[350px] break-words ">
            🤖 AI - powered editing, effects, and captions.⚡Create stunning
            YouTube Shorts and transform your ideas into viral short videos in
            seconds!{" "}
          </motion.p>
          <div className="mt-10 flex gap-6 relative z-20">
            {!user ? (
              <div className="flex gap-2">
                  <Authentication>
                  <Button size={"lg"} variant={"secondary"}>
                    Explore
                  </Button>
                  </Authentication>
              <Authentication>
                <Button size="lg">Get Started</Button>
              </Authentication>
              </div>
            ) : (
              <div className="flex gap-2">
                <Link href={"/explore"}>
                  <Button size={"lg"} variant={"secondary"}>
                    Explore
                  </Button>
                </Link>
                <Link href={"/dashboard"}>
                  <Button size={"lg"}>Dashboard</Button>
                </Link>
              </div>
            )}
          </div>
        </div>
      </div>

      <Ripple />
    </div>
  );
}

export function FlipWordsDemo() {
  const words = ["Create", "Export", "Explore", "Enjoy"];

  return (
    <motion.h1
      className={cn(
        "md:text-7xl text-center text-4xl text-white font-bold lg:px-[200px] break-words relative z-20 "
      )}
    >
      <FlipWords words={words} />
      Short Videos Generated by <AuroraText>AI</AuroraText>
    </motion.h1>
  );
}

export function AnimatedShinyTextDemo() {
  return (
    <div className="z-10 flex  transform -translate-y-10 items-center justify-center">
      <div
        className={cn(
          "group rounded-full border border-black/5 bg-neutral-100 text-base text-white transition-all ease-in hover:cursor-pointer hover:bg-neutral-200 dark:border-white/5 dark:bg-neutral-900 dark:hover:bg-neutral-800"
        )}
      >
        <AnimatedShinyText className="inline-flex items-center justify-center px-4 py-1 transition ease-out hover:text-neutral-600 hover:duration-300 hover:dark:text-neutral-400">
          <span>✨ Introducing Snip AI</span>
          <ArrowRightIcon className="ml-1 size-3 transition-transform duration-300 ease-in-out group-hover:translate-x-0.5" />
        </AnimatedShinyText>
      </div>
    </div>
  );
}

export default Hero;
